// config/locations.ts
// Auto-generated by gen-locations.py — edit freely
// Each entry creates an SEO page at /locations/[slug]

export interface Location {
  slug:        string;
  name:        string;
  city:        string;
  stateCode:   string;
  description: string;
  distance:    string;
  landmarks:   string[];
}

export const locations: Location[] = [
  {
    slug:        "henderson-nv",
    name:        "Henderson, NV",
    city:        "Henderson",
    stateCode:   "NV",
    description: "Henderson is a vibrant city known for its family-friendly atmosphere and outdoor recreational opportunities.",
    distance:    "16 miles southeast of Las Vegas city center",
    landmarks:   ["Lake Las Vegas", "Henderson Bird Viewing Preserve", "The District at Green Valley Ranch"],
  },
  {
    slug:        "summerlin-nv",
    name:        "Summerlin, NV",
    city:        "Las Vegas",
    stateCode:   "NV",
    description: "Summerlin is a master-planned community known for its upscale living, golf courses, and proximity to Red Rock Canyon.",
    distance:    "12 miles west of Las Vegas city center",
    landmarks:   ["Red Rock Canyon National Conservation Area", "Downtown Summerlin", "TPC Summerlin"],
  },
  {
    slug:        "north-las-vegas-nv",
    name:        "North Las Vegas, NV",
    city:        "North Las Vegas",
    stateCode:   "NV",
    description: "North Las Vegas is a growing community with a mix of residential, commercial, and industrial areas.",
    distance:    "5 miles north of Las Vegas city center",
    landmarks:   ["Aliante Nature Discovery Park", "Craig Ranch Regional Park", "Cannery Casino Hotel"],
  },
  {
    slug:        "paradise-nv",
    name:        "Paradise, NV",
    city:        "Paradise",
    stateCode:   "NV",
    description: "Paradise is home to the Las Vegas Strip and offers a bustling nightlife and entertainment scene.",
    distance:    "3 miles south of Las Vegas city center",
    landmarks:   ["The Las Vegas Strip", "University of Nevada, Las Vegas", "McCarran International Airport"],
  },
  {
    slug:        "spring-valley-nv",
    name:        "Spring Valley, NV",
    city:        "Spring Valley",
    stateCode:   "NV",
    description: "Spring Valley is a suburban area known for its diverse community and proximity to the Las Vegas Strip.",
    distance:    "7 miles southwest of Las Vegas city center",
    landmarks:   ["Desert Breeze Park", "Spring Valley Library", "Spanish Trail Country Club"],
  },
  {
    slug:        "enterprise-nv",
    name:        "Enterprise, NV",
    city:        "Enterprise",
    stateCode:   "NV",
    description: "Enterprise is a rapidly growing area with a mix of residential communities and commercial developments.",
    distance:    "10 miles southwest of Las Vegas city center",
    landmarks:   ["Mountain's Edge Regional Park", "Exploration Peak Park", "Rhodes Ranch Golf Club"],
  },
  {
    slug:        "boulder-city-nv",
    name:        "Boulder City, NV",
    city:        "Boulder City",
    stateCode:   "NV",
    description: "Boulder City is a quaint town known for its small-town charm and proximity to Hoover Dam.",
    distance:    "26 miles southeast of Las Vegas city center",
    landmarks:   ["Hoover Dam", "Lake Mead National Recreation Area", "Boulder City/Hoover Dam Museum"],
  },
  {
    slug:        "winchester-nv",
    name:        "Winchester, NV",
    city:        "Winchester",
    stateCode:   "NV",
    description: "Winchester is a residential area with a mix of older homes and new developments, close to the Las Vegas Strip.",
    distance:    "4 miles east of Las Vegas city center",
    landmarks:   ["Las Vegas National Golf Club", "Boulevard Mall", "Winchester Cultural Center"],
  },
];
